### ISSUE TITLE
Data for update from_form not doing any update

### ISSUE THREAD

**Issue by shinningweb** [avenirer/CodeIgniter-MY_Model#226] opened 2017-03-15 08:24 UTC
In the controller,

if($this->input->post('user_id')){
	$this->users_model->from_form(NULL,NULL,array('user_id'))->update(); 
}

the insert from form is working perfectly.
if i try using the update method, it works but unable to validate

**Comment by emrahoruc** [comment] 2017-03-15 08:51
Cause, you have no any post request. But, You can create your own then call the from_form.

```php
$_POST['field1'] = 1; 
$_POST['field2'] = 2; 

$this->users_model->from_form(NULL,NULL,array('user_id'))->update();
```

**Comment by shinningweb** [comment] 2017-03-15 08:56
I am sending a form from view, from the bench mark, all the fields are posting correctly

**Comment by shinningweb** [comment] 2017-03-15 08:58
//look for ID in URI and store it in a variable
	if($this->uri->segment(3)){
    $rec_id = $this->uri->segment(3);

    //check DB to see if record exists, if it does keep as an array called $regions
    $record_id = $this->users_model->get($rec_id);
    if($record_id){
    $data['recs'] = $record_id;
    $data['users'] = $record_id['pub_name'];
    } else { $data['users'] = 'No matching record found';}
	} else {
    	$data['recs'] = [];
    	$data['title'] = 'New reg title';
    }
	
	//if we have an ID, it is an update
	if($this->input->post('user_id')){
	$this->users_model->from_form(NULL,NULL,array('user_id'=>'12'),NULL)->update(); 
	
   $id = TRUE;
	} else {
    
    //we are doing an insert by default when this controller is evoked
   	$id = $this->users_model->from_form()->insert();}

    if($id === FALSE)
    {

    $data['title'] = 'Register an account';
        $data['page'] = $this->load->view('member/register', $data, TRUE);
		$this->load->view('main', $data);
        
    }
    else //insert was successful, redirect to list of users
    {
       redirect('page/register_success','refresh');
      
       
    }

}

**Comment by emrahoruc** [comment] 2017-03-15 09:01
Oh, i got it wrong. Did you set the validation rules in Users_model ?

**Comment by shinningweb** [comment] 2017-03-15 09:01
'update' => array(
            
            'pub_name' => array('field'=>'pub_name',
                        'label'=>'Name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'              
                        ),
            'pub_firm' => array('field'=>'pub_firm',
                        'label'=>'Company name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'  
                        ),
            'pub_city' => array('field'=>'pub_city',
                        'label'=>'City',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'  
                        ),
            'pub_tel' => array('field'=>'pub_tel',
                        'label'=>'Telephone',
                        'rules'=>'trim|required|is_numeric'                      
                        ),
            'pub_mob' => array('field'=>'pub_mob',
                        'label'=>'Mobile Phone',
                        'rules'=>'trim|required|is_numeric'                      
                        ),
            'pub_address' => array('field'=>'pub_address',
                        'label'=>'Address',
                        'rules'=>'trim|min_length[5]|max_length[255]'                      
                        ),
            'pub_web' => array('field'=>'pub_web',
                        'label'=>'website',
                        'rules'=>'trim|max_length[50]'                      
                        )
            )                    
    );

**Comment by shinningweb** [comment] 2017-03-15 09:02
i do have similar thing for the insert as well

**Comment by salain** [comment] 2017-03-15 10:02
Your call to from_form is wrong 

```php
$this->users_model->from_form(NULL,NULL,array('user_id'=>'12'),NULL)->update(); 
//should be 
$this->users_model->from_form(NULL,NULL,array('user_id'=>'12'))->update(); 
```
Let us know if it works

**Comment by shinningweb** [comment] 2017-03-15 11:11
its updated, still not working

**Comment by shinningweb** [comment] 2017-03-15 11:26
it returns boolean false

**Comment by salain** [comment] 2017-03-15 11:26
Not sure what the issue is but I think you may have an error here:

```php
if($this->uri->segment(3)){
$rec_id = $this->uri->segment(3);

//check DB to see if record exists, if it does keep as an array called $regions
$record_id = $this->users_model->get($rec_id);
if($record_id){
$data['recs'] = $record_id;
$data['users'] = $record_id['pub_name'];
} else { $data['users'] = 'No matching record found';}  // <- I think you have one too many curly brace
} else {
	$data['recs'] = [];
	$data['title'] = 'New reg title';
}

```
If this is not the case use some debug code to see where it goes wrong.

**Comment by shinningweb** [comment] 2017-03-15 11:27
those codes are used in the view page, they are not part of the query

**Comment by shinningweb** [comment] 2017-03-15 11:28
when i debug, it gives me bool false, when i debug the post array, it shows me every post array excellently

**Comment by salain** [comment] 2017-03-15 11:52
it returns FALSE, it maybe your validation that fail, try to relax your rules to see if that works.

**Comment by shinningweb** [comment] 2017-03-15 12:17
i have removed all the rules except one, still not working

**Comment by salain** [comment] 2017-03-15 12:34
If you try a direct update, does it work ?
do you use the latest MY_Model and what version of CI are you using ?
If you show a bit more code it maybe easier to help you out rather then guessing

**Comment by shinningweb** [comment] 2017-03-15 12:40
Model

<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
* 
*/
class Users_model extends MY_Model
//region_name, region_head, region_admin, region_office, region_phone, region_email, region_desc
{
    public $table = 'users'; // you MUST mention the table name
    public $primary_key = 'user_id'; // you MUST mention the primary key
    //public $table_fields = array('region_id','region_name','region_head','region_admin','region_office_address','region_phone','region_email');
public $fillable = array('pub_name','pub_tel','pub_mob','pub_address','pub_email','pub_web','specialization','password','pub_firm','pub_city'); // If you want, you can set an array with the fields that can be filled by insert/update
    //public $protected = array('created_at','updated_at'); // ...Or you can set an array with the fields that cannot be filled by insert/update
    
    public function __construct()
    {
        parent::__construct();
        $this->return_as = 'array';
    }

    
    public $rules = array(
    
        'insert' => array(

            'pub_name' => array('field'=>'pub_name',
                        'label'=>'Name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'              
                        ),
            'pub_firm' => array('field'=>'pub_firm',
                        'label'=>'Company name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'  
                        ),
            'pub_city' => array('field'=>'pub_city',
                        'label'=>'City',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'  
                        ),
            'pub_tel' => array('field'=>'pub_tel',
                        'label'=>'Telephone',
                        'rules'=>'trim|required|is_numeric'                      
                        ),
            'pub_mob' => array('field'=>'pub_mob',
                        'label'=>'Mobile Phone',
                        'rules'=>'trim|required|is_numeric'                      
                        ),
            'pub_address' => array('field'=>'pub_address',
                        'label'=>'Address',
                        'rules'=>'trim|min_length[5]|max_length[255]'                      
                        ),
            'pub_web' => array('field'=>'pub_web',
                        'label'=>'website',
                        'rules'=>'trim|max_length[50]'                      
                        ),
             'password' => array('field'=>'password',
                        'label'=>'password',
                        'rules'=>'required|md5'                      
                        ),

            'pub_email' => array(
                        'field'=>'pub_email',
                        'label'=>'Email',
                        'rules'=>'trim|valid_email|required',
                        'errors' => array ('required' => 'Username/ Email is required',
                                'trim' => 'Error message for rule trim for field email',
                                'valid_email' => 'Email should be valid')
                    )
              ),    
                
        'update' => array(
            
            'pub_name' => array('field'=>'pub_name',
                        'label'=>'Name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'              
                        )
           
            )                    
    );
    
    
}


View

<?php 
if (is_array($recs)){
   $rec = $recs;
} else {
    $rec = array(
    'user_id'=>'',
    'pub_name'=>'',
    'pub_tel'=>'',
    'pub_mob'=>'',
    'pub_firm'=>'',
    'pub_email'=>'',
    'pub_web'=>'',
    'pub_address'=>'',
    'pub_city'=>'',
    'specialization'=>'',
    );
}

?>

      
      <div id="content">
        
        <div class="breadcrumb"> <a href="<?php echo base_url();?>">Home</a> » <a href="#">Dashboard</a>  </div>
        
        <h1>Welcome Guest for now</h1>
       
        <form enctype="multipart/form-data" method="post" action="<?php echo base_url();?>page/go">
          <h2>Your Personal Details</h2>
            <?php var_dump($recs);?>
          <div class="content">
            <table class="form">
              <tbody>
                <tr>
                  <td><span class="required">*</span> Name:</td>
                    <input type="text" name="user_id" value="<?php echo $rec['user_id'];?>">
                    
                  <td> <?php echo form_error('pub_name'); ?> <input class="large-field" type="text" value="<?php echo ($rec['pub_name']); ?>" name="pub_name"></td>
                </tr>
                <tr>
                  <td><span class="required">*</span> Office Phone</td>
                    
                  <td><?php echo form_error('pub_tel'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_tel']); ?>" name="pub_tel"></td>
                </tr>
                  
                  <tr>
                  <td><span class="required">*</span> Mobile Phone</td>
                  <td><?php echo form_error('pub_mob'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_mob']); ?>" name="pub_mob"></td>
                </tr>
              
                <tr>
                  <td><span class="required">*</span> Website</td>
                  <td><?php echo form_error('pub_web'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_web']); ?>" name="pub_web"></td>
                </tr>
                
              </tbody>
            </table>
          </div>
          <h2>Your Address</h2>
          <div class="content">
            <table class="form">
              <tbody>
                <tr>
                  <td>Company name:</td>
                  <td><?php echo form_error('pub_firm'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_firm']); ?>" name="pub_firm"></td>
                </tr>
              
                <tr>
                  <td><span class="required">*</span> Company Address</td>
                  <td><?php echo form_error('pub_address'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_address']); ?>" name="pub_address"></td>
                </tr>
                
                <tr>
                  <td><span class="required">*</span> City:</td>
                  <td><?php echo form_error('pub_city'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_city']); ?>" name="pub_city"></td>
                </tr>
               
                <tr>
                  <td><span class="required">*</span> Specialty:</td>
                  <td>
                      
                    <select>
                    <option value="General" <?php echo ($rec['specialization']=='General')? 'selected':'';?> >General</option>
                    <option value="Children" <?php echo ($rec['specialization']=='Children')? 'selected':'';?>>Children</option>
                    <option value="Literature" <?php echo ($rec['specialization']=='Literature')? 'selected':'';?>>Literature</option>
                    <option value="Religious" <?php echo ($rec['specialization']=='Religious')? 'selected':'';?>>Religious</option>
                    </select>
                    
                    </td>
                </tr>
               
              </tbody>
            </table>
          </div>
         
          
          <div class="buttons">
            <div class="left">
             
              <input type="submit" class="button" value="Update">
            </div>
          </div>
          </form>
          


Controller

//look for ID in URI and store it in a variable
	if($this->uri->segment(3)){
    $rec_id = $this->uri->segment(3);

    //check DB to see if record exists, if it does keep as an array called $regions
    $record_id = $this->users_model->get($rec_id);
    if($record_id)
    {
        $data['recs'] = $record_id;
        $data['title'] = $record_id['pub_name'];
    } else { 
      $data['users'] = 'No matching record found';
    
    }
	} else {
    	$data['recs'] = [];
    	$data['title'] = 'New registration';
    }
	
	//if we have an ID, it is an update
	if($this->input->post('user_id')){
    
	$this->users_model->from_form(NULL,NULL,array('user_id'))->update(); 
	
   $id = TRUE;
	} else {
    
    //we are doing an insert by default when this controller is evoked
   	$id = $this->users_model->from_form()->insert();}

    if($id === FALSE)
    {

    $data['title'] = 'Register an account';
        $data['page'] = $this->load->view('member/register', $data, TRUE);
		$this->load->view('main', $data);
        
    }
    else //insert was successful, redirect to list of users
    {
       redirect('page/register_success','refresh');
       
    }

}

**Comment by shinningweb** [comment] 2017-03-15 12:41
The from_form insert works perfectly, the update method also works perfectly, but am unable to validate when using the update method, NOT UPDATE from_form, i mean raw update from array data. ($_POST)

**Comment by shinningweb** [comment] 2017-03-15 12:45
i have updated to the latest one as well, MY_Model, am using CI 3

**Comment by avenirer** [comment] 2017-03-15 12:49
Soo... update from the form works... but the method update() doesn't?

**Comment by salain** [comment] 2017-03-15 12:54
Ok, CI 3 at some point (3.1.2, I think) had a bug in the update method last 0ne 3.1.3 work.

Also you need a validation rule for every field you want to update, so if for field that don't have any constraint just use trim as a rule. 
@avenirer no from_form(...)->update() does not work

**Comment by shinningweb** [comment] 2017-03-15 12:58
no, the update from_form does not work

**Comment by avenirer** [comment] 2017-03-15 13:00
update the CI to latest version, and tell us if you still have problems.

**Comment by shinningweb** [comment] 2017-03-15 13:05
Done, still not updating. Is there a way to use just the update method and validate before insert?

**Comment by shinningweb** [comment] 2017-03-15 13:06
the update method works perfectly, but no way to validate data

**Comment by avenirer** [comment] 2017-03-15 13:13
ok... i see where the problem might be... just a minute or so...

**Comment by avenirer** [comment] 2017-03-15 13:17
can you send me the controller, the model and the view... i can see it more clearly this way. send at avenir.ro@gmail.com

**Comment by avenirer** [comment] 2017-03-15 13:19
but why do you put fields with no validation in the rules? put at least the trim if nothing else...

**Comment by avenirer** [comment] 2017-03-15 13:20
also... i see you have a select in there for specialty... which in the view doesn't have the name, nor the form error output.

**Comment by shinningweb** [comment] 2017-03-15 13:22
does every field need to be validated? because the id and the email address should not be changed when updating

**Comment by avenirer** [comment] 2017-03-15 13:22
then why add them to validation?

**Comment by avenirer** [comment] 2017-03-15 13:23
and you can also define protected fields, if you want to make sure no one changes them.

**Comment by shinningweb** [comment] 2017-03-15 13:24
I have sent the three files by mail

**Comment by salain** [comment] 2017-03-16 06:38
Out of curiosity, has this been solved and what was the issue?

**Comment by shinningweb** [comment] 2017-03-16 06:51
not solved.

**Comment by avenirer** [comment] 2017-03-16 07:42
I haven't received them yet. Could you send them again?

**Comment by shinningweb** [comment] 2017-03-16 08:58
let me paste them here


[Archive.zip](https://github.com/avenirer/CodeIgniter-MY_Model/files/847154/Archive.zip)

**Comment by avenirer** [comment] 2017-03-16 10:17
I don't see user_id in your form.

**Comment by shinningweb** [comment] 2017-03-16 10:24
line 36

**Comment by avenirer** [comment] 2017-03-16 10:25
in your form... there is no user_id

**Comment by shinningweb** [comment] 2017-03-16 10:27
register.php line 36 has user_id name field

**Comment by salain** [comment] 2017-03-16 10:31
none of the fields in the form match the validation rules 
register.php line 36 is the telephone label. 
It seams you have the wrong files

**Comment by shinningweb** [comment] 2017-03-16 10:34
[register.php.zip](https://github.com/avenirer/CodeIgniter-MY_Model/files/847416/register.php.zip)
sorry, sent the wrong file

**Comment by shinningweb** [comment] 2017-03-16 13:13
I have found the fix. The problem is with the CI version, 3.0.0 works fine with the older version of MY_Model, which i downloaded more than a year ago. This new MY_Model does not work well with CI 3.1.3 or CI 3.0, so new MY_Model need some revision, but thanks for the good work and support

**Comment by avenirer** [comment] 2017-03-16 13:29
Wow... such a conclusion... Can you tell me what older version of MY_Model are you using? Because, as I remember, the from_form() method is not really older than a year (or is it?) and I don't remember doing radical changes to the from_form() since I first created it.

**Comment by shinningweb** [comment] 2017-03-16 13:31
* Copyright (C) 2014 @avenirer [avenir.ro@gmail.com]

**Comment by shinningweb** [comment] 2017-03-16 13:34
they are very much different, the "from_from" for old...

  public function from_form($rules = NULL,$additional_values = NULL, $row_fields_to_update = array())
    {
        $this->_get_table_fields();
        $this->load->library('form_validation');
        if(!isset($rules))
        {
            if(empty($row_fields_to_update))
            {
                $rules = $this->rules['insert'];
            }
            else
            {
                $rules = $this->rules['update'];
            }
        }
        $this->form_validation->set_rules($rules);
        if($this->form_validation->run())
        {
            $this->fillable_fields();
            $this->validated = array();
            foreach($rules as $rule)
            {
                if(in_array($rule['field'],$this->_can_be_filled))
                {
                    $this->validated[$rule['field']] = $this->input->post($rule['field']);
                }
            }
            if(isset($additional_values) && is_array($additional_values) && !empty($additional_values))
            {
                foreach($additional_values as $field => $value)
                {
                    if(in_array($field, $this->_can_be_filled))
                    {
                        $this->validated[$field] = $value;
                    }
                }
            }
            if(!empty($row_fields_to_update))
            {
                foreach ($row_fields_to_update as $key => $field) {
                    if (in_array($field, $this->table_fields)) {
                        $this->row_fields_to_update[$field] = $this->input->post($field);
                    }
                    else if (in_array($key, $this->table_fields)){
                        $this->row_fields_to_update[$key] = $field;
                    }
                    else {
                        continue;
                    }
                }
            }
            return $this;
        }
        else
        {
            $this->validated = FALSE;
            return $this;
        }
    }

**Comment by shinningweb** [comment] 2017-03-16 13:34
from form new...

 public function from_form($rules = NULL,$additional_values = NULL, $row_fields_to_update = array())
    {
        $this->_get_table_fields();
        $this->load->library('form_validation');
        if(!isset($rules))
        {
            $rules = $this->rules;
        }
        $this->form_validation->set_rules($rules);
        if($this->form_validation->run())
        {
            $this->fillable_fields();
            $this->validated = array();
            foreach($rules as $rule)
            {
                if(in_array($rule['field'],$this->_can_be_filled))
                {
                    $this->validated[$rule['field']] = $this->input->post($rule['field']);
                }
            }
            if(isset($additional_values) && is_array($additional_values) && !empty($additional_values))
            {
                foreach($additional_values as $field => $value)
                {
                    if(in_array($field, $this->_can_be_filled))
                    {
                        $this->validated[$field] = $value;
                    }
                }
            }

            if(!empty($row_fields_to_update))
            {
                foreach ($row_fields_to_update as $key => $field) {
                    if (in_array($field, $this->table_fields)) {
                        $this->row_fields_to_update[$field] = $this->input->post($field);
                    }
                    else if (in_array($key, $this->table_fields)){
                        $this->row_fields_to_update[$key] = $field;
                    }
                    else {
                        continue;
                    }
                }
            }
            return $this;
        }
        else
        {
            $this->validated = FALSE;
            return $this;
        }

    }

**Comment by avenirer** [comment] 2017-03-16 13:46
The only difference between the two is the fact that the rules are differentiated depending on insert or update. That means that if you use the old version, you won't have different rules for insert and update.

The only thing that comes to my mind regarding your error is the fact that you only had one rule for update and that would have returned as false, as you don't have the user_id among the validation rules.

The model knows what fields needs to be updated by looking at the validation rules.

So my advice would be for you to use the latest MY_Model and, create validation rules for all the fields you want updated (even if the only rule is "trim"; by the way, I don't think you can have a validation rule without any rules, as you tried).

**Comment by shinningweb** [comment] 2017-03-16 14:30
it is not still working

**Comment by shinningweb** [comment] 2017-03-16 14:31
may be you should look again

**Comment by avenirer** [comment] 2017-03-16 15:40
Hello again. Just to be sure, I tested the MY_Model creating an update form from zero, and adding rules for every field that I wanted updated. My test worked. I will close this issue, as no one else complained about it not working. I am sorry if this upsets you.

**Closed as completed by avenirer** 2017-03-16 15:40 UTC

**Comment by pudjamansyurin** [comment] 2018-07-13 00:55
For method with PUT request, you have to hack the MY_Model file, in from_form function, change $this->input->post() to $this->input->input_stream()

**Comment by GarageTech** [comment] 2018-12-26 15:41
Hi!
Have the similar problem with from_form().
I copy full example from your page:
https://avenir.ro/how-to-edit-a-row-of-data-with-a-form-in-codeigniter/

But problem is - changes take all records in table. No 'id' field pass to MySQL.
When i add profiler to script i see that sql query run like:
UPDATE groups SET name = '4444'
WHERE 0 = 'id'

If i write:
$this->groups_model->from_form(NULL,array('id' => $id),array('id'))->where_id($id)->update()
all is ok. I add where_id($id) in chain.

Maybe from_form itself have some problems?
All software is latest - apache 2.4 php 7.3.0, codeigniter 3.1.9

Can you help?

**Comment by pudjamansyurin** [comment] 2019-01-02 16:12
it  `from_form(NULL,array('id' => $id),array('id'))` should be like this 

> from_form(NULL,array('id' => $id))

**Comment by GarageTech** [comment] 2019-01-02 18:03
From MY_Model.php - from_form has a three parameters:
public function from_form($rules = NULL,$additional_values = NULL, $row_fields_to_update = array())

**Comment by shinningweb** [comment] 2019-02-23 08:55
You will need to pass the ID from the form, and do this $this->model_name->from_form(NULL,NULL,array('id_field'))->update();
